"""Add countries.iso3column

Revision ID: 44e877c74a27
Revises: 4c14c7925eb2
Create Date: 2021-04-16 17:41:17.663608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44e877c74a27'
down_revision = '4c14c7925eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso3code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'iso3code')
    # ### end Alembic commands ###
